version: "3.6"

services:
  duet_web_control:
    container_name: duetwebcontrol
    build:
      context: ../DuetWebControl
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  # portainer-ce:
  #   container_name: portainer-ce
  #   image: portainer/portainer-ce
  #   restart: unless-stopped
  #   ports:
  #   - "9000:9000"
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   - ./volumes/portainer-ce/data:/data
